import os
import time
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
from google.cloud import dataplex_v1
from google.api_core.client_options import ClientOptions
from google.api_core.exceptions import AlreadyExists

PROJECT_ID = "gsb-data-driven-sandbox"
LOCATION = "us"
GLOSSARY_ID = "enterprise_business_glossary"
DV_CSV = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "sample_files", "DV_MetadataAsset.csv"))
TERMS_CSV = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "sample_files", "Glossaries - Terms.csv"))

def get_clients():
    opts = ClientOptions(quota_project_id=PROJECT_ID)
    return dataplex_v1.CatalogServiceClient(client_options=opts), dataplex_v1.BusinessGlossaryServiceClient(client_options=opts)

def ensure_us_terms(bg_client):
    print(f"Ensuring regional US Glossary container and terms exist in {LOCATION}...")
    parent_glos = f"projects/{PROJECT_ID}/locations/{LOCATION}/glossaries/{GLOSSARY_ID}"
    
    # Create glossary container if missing
    try:
        glos_obj = dataplex_v1.Glossary(display_name="Enterprise Business Glossary (US)", description="Regional US container matching EDW table location.")
        bg_client.create_glossary(parent=f"projects/{PROJECT_ID}/locations/{LOCATION}", glossary_id=GLOSSARY_ID, glossary=glos_obj)
    except Exception:
        pass

    term_entry_map = {}
    if os.path.exists(TERMS_CSV):
        df_t = pd.read_csv(TERMS_CSV, low_memory=False)
        for idx, r in df_t.iterrows():
            tname = str(r.get('Term Name', '')).strip()
            if not tname:
                continue
            clean_id = ''.join([c for c in tname.lower() if c.isascii() and (c.isalnum() or c == '-')]).strip("-")[:50] or f"term-{idx}"
            term_uri = f"{parent_glos}/terms/{clean_id}"
            
            # Entry URI generated by Dataplex for regional US terms
            entry_uri = f"projects/{PROJECT_ID}/locations/{LOCATION}/entryGroups/{GLOSSARY_ID}/entries/{clean_id}"
            term_entry_map[tname.lower().strip()] = entry_uri
            
            # Onboard top 50 terms to US region
            if idx < 50:
                try:
                    t_obj = dataplex_v1.GlossaryTerm(display_name=tname[:200], description=str(r.get('Description', 'Standard term'))[:2000])
                    bg_client.create_glossary_term(parent=parent_glos, term_id=clean_id, term=t_obj)
                except Exception:
                    pass
    return term_entry_map

def bind_console_link(dp_client, table_entry_uri, col_name, term_entry_uri, link_id):
    parent_group = f"projects/{PROJECT_ID}/locations/{LOCATION}/entryGroups/@bigquery"
    ltype = f"projects/{PROJECT_ID}/locations/{LOCATION}/entryLinkTypes/definition"
    
    link_obj = dataplex_v1.EntryLink(
        entry_link_type=ltype,
        entry_references=[
            dataplex_v1.EntryLink.EntryReference(name=table_entry_uri, path=f"schema.fields.{col_name}", type_="SOURCE"),
            dataplex_v1.EntryLink.EntryReference(name=term_entry_uri, type_="TARGET")
        ]
    )
    req = dataplex_v1.CreateEntryLinkRequest(parent=parent_group, entry_link_id=link_id[:63], entry_link=link_obj)
    try:
        dp_client.create_entry_link(request=req)
        return True
    except AlreadyExists:
        return "Exists"
    except Exception as e:
        return f"Err ({col_name}): {e}"

def main():
    start_t = time.time()
    print("=== Native Google Cloud Console Bulk Business Term UI Sync Engine ===")
    dp_client, bg_client = get_clients()
    
    term_entry_map = ensure_us_terms(bg_client)
    
    print(f"Parsing {DV_CSV} for physical column matches...")
    df = pd.read_csv(DV_CSV, low_memory=False, skiprows=1)
    
    links_to_create = []
    seen = set()
    
    for _, row in df.iterrows():
        raw_id = str(row.get('id', '')).strip()
        tname = str(row.get('Source Description', '')).strip()
        if not raw_id.startswith("DV://BLUDB/") or not tname:
            continue
        tkey = tname.lower().strip()
        if tkey not in term_entry_map:
            continue
        term_entry_uri = term_entry_map[tkey]
        parts = raw_id.split("/")
        if len(parts) < 6:
            continue
        dataset = parts[3].lower()
        t_name_clean = parts[4].lower()
        col_name = parts[5].lower()
        
        table_entry_uri = f"projects/{PROJECT_ID}/locations/{LOCATION}/entryGroups/@bigquery/entries/bigquery.googleapis.com/projects/{PROJECT_ID}/datasets/{dataset}/tables/{t_name_clean}"
        lid = f"ui-{dataset[:4]}-{t_name_clean[:18]}-{col_name[:20]}".replace("_", "-")
        if lid in seen:
            continue
        seen.add(lid)
        links_to_create.append((table_entry_uri, col_name, term_entry_uri, lid))

    print(f"Discovered {len(links_to_create)} exact regional matches! Executing concurrent Console UI synchronization...")
    
    success = 0
    existed = 0
    notes = []
    with ThreadPoolExecutor(max_workers=10) as exe:
        futs = [exe.submit(bind_console_link, dp_client, t_uri, col, term, lid) for t_uri, col, term, lid in links_to_create[:50]]
        for f in as_completed(futs):
            res = f.result()
            if res is True:
                success += 1
            elif res == "Exists":
                existed += 1
            else:
                notes.append(res)

    dur = round(time.time() - start_t, 2)
    print(f"\n🎉 Native Console UI Sync Complete in {dur}s!")
    print(f"✅ Synchronized {success + existed} formal EntryLink relationships to Google Cloud Console!")
    if notes:
        print(f"First 3 notes: {notes[:3]}")

if __name__ == "__main__":
    main()
